=== hemantkgupta/XML/OJAX3-Book-Ch08-StAX/contacts.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<!ELEMENT address (line+, city, state, zip)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT contact (name, address)>
<!ELEMENT contacts (contact+)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT name (first, middle?, last)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT zip (#PCDATA)>

=== hemantkgupta/XML/OJAX3-Book-Ch08-StAX/lola.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacts SYSTEM "sample/contacts.dtd">
<contacts>
	<contact>
		<name>
			<first>Lola</first>
			<last>Hires</last>
		</name>
		<address>
			<line>PO Box 208</line>
			<city>Crompond</city>
			<state>NY</state>
			<zip>10517</zip>
		</address>
	</contact>
	<contact>
		<name>
			<first><![CDATA[Burt]]></first>
			<middle>Bachrach</middle>
			<last>Hires</last>
		</name>
		<address>
			<line>57 Townsend Road</line>
			<line>PO Box 208</line>
			<city>Crompond</city>
			<state>NY</state>
			<zip>10517</zip>
		</address>
	</contact>
</contacts>
